#!/usr/bin/env zsh
set -euo pipefail

############################################
# 基础配置
############################################

MODULE="github.com/zy84338719/ikuai-tools-service"
IDL_DIR="idl"
HZ_OUT_DIR="."                        # hz --out_dir，相对于项目根（.hz 在此目录）
HANDLER_DIR="gen/http/handler"        # 相对于 HZ_OUT_DIR
MODEL_DIR="gen/http/model"            # 相对于 HZ_OUT_DIR
ROUTER_DIR="gen/http/router"          # 相对于 HZ_OUT_DIR
HZ_META_FILE=".hz"                    # .hz 位置（out_dir 根）
RPC_OUT_DIR="gen/rpc"

############################################
# 工具函数
############################################

log() {
  echo -e "\033[1;32m[INFO]\033[0m $1"
}

warn() {
  echo -e "\033[1;33m[WARN]\033[0m $1"
}

err() {
  echo -e "\033[1;31m[ERROR]\033[0m $1"
  exit 1
}

check_hz() {
  if ! command -v hz &> /dev/null; then
    err "hz 未安装，请执行：go install github.com/cloudwego/hertz/cmd/hz@latest"
  fi
}

check_kitex() {
  if ! command -v kitex &> /dev/null; then
    err "kitex 未安装，请执行：go install github.com/cloudwego/kitex/tool/cmd/kitex@latest"
  fi
}

############################################
# 使用说明
############################################

usage() {
  echo "Usage:"
  echo "  ./scripts/gen.sh <command> [idl_file]"
  echo ""
  echo "Commands:"
  echo "  hz-new          初始化 Hz HTTP 项目（指定单个 IDL）"
  echo "  hz-update       更新 Hz HTTP 代码（指定单个 IDL，.hz 不存在时自动初始化）"
  echo "  hz-update-all   扫描所有 idl/*.proto 和 idl/http/*.proto 批量更新"
  echo "  hz-init         强制重新初始化 .hz 配置（备份 handler 后 hz new --force）"
  echo "  kitex           生成 Kitex RPC 代码（指定单个 IDL）"
  echo ""
  echo "Examples:"
  echo "  ./scripts/gen.sh hz-new idl/common.proto"
  echo "  ./scripts/gen.sh hz-update idl/common.proto"
  echo "  ./scripts/gen.sh hz-update idl/http/health.proto"
  echo "  ./scripts/gen.sh hz-update-all"
  echo "  ./scripts/gen.sh hz-init idl/common.proto"
  echo "  ./scripts/gen.sh kitex idl/rpc/user.proto"
  exit 1
}

############################################
# 参数解析
############################################

if [[ $# -lt 1 ]]; then
  usage
fi

ACTION=$1
IDL_FILE="${2:-}"

############################################
# 防止生成到 biz/
############################################

if [[ -d "biz" ]]; then
  err "检测到 biz/ 目录，请删除或迁移，避免生成到错误目录"
fi

############################################
# 核心函数：创建 .hz 元数据文件
############################################

_ensure_hz_meta() {
  if [[ ! -f "$HZ_META_FILE" ]]; then
    warn ".hz 配置文件不存在，自动创建..."
    printf '// Code generated by hz. DO NOT EDIT.\n\nhz version: v0.9.7\nhandlerDir: %s\nmodelDir: %s\nrouterDir: %s\n' \
      "$HANDLER_DIR" "$MODEL_DIR" "$ROUTER_DIR" > "$HZ_META_FILE"
    log ".hz 创建完成"
  fi
}

############################################
# 核心函数：构建 --exclude_file 参数列表
# 保护已存在的 handler 文件不被 hz 覆盖
############################################

_build_exclude_args() {
  local result_name=$1
  local -a files=()
  while IFS= read -r -d '' f; do
    files+=("-E" "$f")
  done < <(find "$HANDLER_DIR" -name "*.go" -print0 2>/dev/null)
  eval "${result_name}=(\"\${files[@]}\")"
}

############################################
# 核心函数：判断是否需要 -I IDL_DIR
# IDL 文件在 idl/ 根目录时不加（避免 shadowing）
# IDL 文件在子目录时必须加（解析 import "api/api.proto"）
############################################

_build_proto_path_args() {
  local result_name=$1
  local idl_file=$2
  local idl_dir
  idl_dir="$(dirname "$idl_file")"
  local -a args=()
  # 如果 IDL 文件不在 IDL_DIR 根目录，需要添加 -I 让 protoc 找到依赖
  if [[ "$idl_dir" != "$IDL_DIR" ]]; then
    args+=("-I" "$IDL_DIR")
  fi
  eval "${result_name}=(\"\${args[@]}\")"
}

############################################
# Hz HTTP 代码生成
############################################

gen_hz_new() {
  check_hz
  if [[ -z "$IDL_FILE" ]]; then
    err "hz-new 需要指定 IDL 文件，用法: ./scripts/gen.sh hz-new idl/common.proto"
  fi
  if [[ ! -f "$IDL_FILE" ]]; then
    err "IDL 文件不存在: $IDL_FILE"
  fi

  mkdir -p "$HANDLER_DIR" "$MODEL_DIR" "$ROUTER_DIR"

  local proto_path_args
  _build_proto_path_args proto_path_args "$IDL_FILE"

  log "执行 hz new: $IDL_FILE"
  hz new \
    --idl "$IDL_FILE" \
    --module "$MODULE" \
    --out_dir "$HZ_OUT_DIR" \
    --handler_dir "$HANDLER_DIR" \
    --model_dir "$MODEL_DIR" \
    --router_dir "$ROUTER_DIR" \
    "${proto_path_args[@]+"${proto_path_args[@]}"}"
  _fix_hz_meta
}

gen_hz_init() {
  check_hz
  if [[ -z "$IDL_FILE" ]]; then
    err "hz-init 需要指定 IDL 文件，用法: ./scripts/gen.sh hz-init idl/common.proto"
  fi
  if [[ ! -f "$IDL_FILE" ]]; then
    err "IDL 文件不存在: $IDL_FILE"
  fi

  mkdir -p "$HANDLER_DIR" "$MODEL_DIR" "$ROUTER_DIR"

  # 备份现有 handler 目录
  local handler_backup="/tmp/hz_handler_backup_$$"
  if [[ -d "$HANDLER_DIR" ]]; then
    cp -r "$HANDLER_DIR" "$handler_backup"
    log "已备份 ${HANDLER_DIR} -> ${handler_backup}"
  fi

  local proto_path_args
  _build_proto_path_args proto_path_args "$IDL_FILE"

  log "强制重新初始化 (hz new --force): $IDL_FILE"
  hz new \
    --idl "$IDL_FILE" \
    --module "$MODULE" \
    --out_dir "$HZ_OUT_DIR" \
    --handler_dir "$HANDLER_DIR" \
    --model_dir "$MODEL_DIR" \
    --router_dir "$ROUTER_DIR" \
    "${proto_path_args[@]+"${proto_path_args[@]}"}" \
    --force

  # 恢复 handler 目录
  if [[ -d "$handler_backup" ]]; then
    cp -r "$handler_backup/." "$HANDLER_DIR/"
    rm -rf "$handler_backup"
    log "已恢复 ${HANDLER_DIR}"
  fi

  _fix_hz_meta
}

# hz new 会重置 .hz 的 dirs，重新写入正确值
_fix_hz_meta() {
  printf '// Code generated by hz. DO NOT EDIT.\n\nhz version: v0.9.7\nhandlerDir: %s\nmodelDir: %s\nrouterDir: %s\n' \
    "$HANDLER_DIR" "$MODEL_DIR" "$ROUTER_DIR" > "$HZ_META_FILE"
  log ".hz 已更新为正确的目录配置"
}

gen_hz_update() {
  check_hz
  if [[ -z "$IDL_FILE" ]]; then
    err "hz-update 需要指定 IDL 文件，用法: ./scripts/gen.sh hz-update idl/common.proto"
  fi
  if [[ ! -f "$IDL_FILE" ]]; then
    err "IDL 文件不存在: $IDL_FILE"
  fi

  mkdir -p "$HANDLER_DIR" "$MODEL_DIR" "$ROUTER_DIR"

  # .hz 不存在时自动创建
  _ensure_hz_meta

  # 收集已存在的 handler 文件（保护自定义代码不被覆盖）
  local exclude_args
  _build_exclude_args exclude_args

  # 根据 IDL 文件位置决定是否需要 -I 参数
  local proto_path_args
  _build_proto_path_args proto_path_args "$IDL_FILE"

  log "执行 hz update: $IDL_FILE"
  hz update \
    --idl "$IDL_FILE" \
    --module "$MODULE" \
    --out_dir "$HZ_OUT_DIR" \
    --model_dir "$MODEL_DIR" \
    "${proto_path_args[@]+"${proto_path_args[@]}"}" \
    "${exclude_args[@]+"${exclude_args[@]}"}"
}

gen_hz_update_all() {
  check_hz
  mkdir -p "$HANDLER_DIR" "$MODEL_DIR" "$ROUTER_DIR"

  # 收集所有 HTTP IDL 文件：idl/*.proto + idl/http/*.proto
  local -a idl_files=()
  while IFS= read -r -d '' f; do
    idl_files+=("$f")
  done < <(find "$IDL_DIR" -maxdepth 1 -name "*.proto" -print0 2>/dev/null)
  while IFS= read -r -d '' f; do
    idl_files+=("$f")
  done < <(find "$IDL_DIR/http" -name "*.proto" -print0 2>/dev/null)

  if [[ ${#idl_files[@]} -eq 0 ]]; then
    err "未在 ${IDL_DIR} 或 ${IDL_DIR}/http 中找到任何 .proto 文件"
  fi

  log "共找到 ${#idl_files[@]} 个 IDL 文件，开始批量更新..."

  # 如果 .hz 不存在，先初始化项目
  if [[ ! -f "$HZ_META_FILE" ]]; then
    warn ".hz 不存在，使用第一个 IDL 初始化项目..."
    
    # 获取第一个文件（兼容 zsh 和 bash）
    local first_idl="${idl_files[@]:0:1}"
    log "初始化项目: $first_idl"
    
    local -a proto_path_args=()
    _build_proto_path_args proto_path_args "$first_idl"
    
    hz new \
      --idl "$first_idl" \
      --module "$MODULE" \
      --out_dir "$HZ_OUT_DIR" \
      --handler_dir "$HANDLER_DIR" \
      --model_dir "$MODEL_DIR" \
      --router_dir "$ROUTER_DIR" \
      "${proto_path_args[@]:+"${proto_path_args[@]}"}"
    
    _fix_hz_meta
    
    # 从列表中移除已处理的第一个文件
    idl_files=("${idl_files[@]:1}")
    
    if [[ ${#idl_files[@]} -eq 0 ]]; then
      log "只有 1 个 IDL 文件，已处理完成"
      return
    fi
  fi

  # 收集已存在的 handler 文件（所有 IDL 共用同一个 exclude 列表）
  local -a exclude_args=()
  _build_exclude_args exclude_args

  local f
  for f in "${idl_files[@]}"; do
    IDL_FILE="$f"
    log "-------------------------------------------"
    log "处理 IDL: $f"

    # 根据 IDL 文件位置决定是否需要 -I 参数
    local -a proto_path_args=()
    _build_proto_path_args proto_path_args "$IDL_FILE"

    log "执行 hz update: $IDL_FILE"
    hz update \
      --idl "$IDL_FILE" \
      --module "$MODULE" \
      --out_dir "$HZ_OUT_DIR" \
      --model_dir "$MODEL_DIR" \
      "${proto_path_args[@]:+"${proto_path_args[@]}"}" \
      "${exclude_args[@]:+"${exclude_args[@]}"}"
  done

  log "==========================================="
  log "批量更新完成，共处理 ${#idl_files[@]} 个 IDL 文件"
}

############################################
# Kitex RPC 代码生成
############################################

gen_kitex() {
  check_kitex
  if [[ -z "$IDL_FILE" ]]; then
    err "kitex 需要指定 IDL 文件，用法: ./scripts/gen.sh kitex idl/rpc/user.proto"
  fi
  if [[ ! -f "$IDL_FILE" ]]; then
    err "IDL 文件不存在: $IDL_FILE"
  fi

  mkdir -p "$RPC_OUT_DIR"
  log "执行 kitex 生成 RPC 代码: $IDL_FILE"
  kitex \
    -module "$MODULE" \
    -gen-path "$RPC_OUT_DIR" \
    -I "$IDL_DIR" \
    "$IDL_FILE"
}

############################################
# 执行生成
############################################

case "$ACTION" in
  hz-new)
    gen_hz_new
    ;;
  hz-update)
    gen_hz_update
    ;;
  hz-update-all)
    gen_hz_update_all
    ;;
  hz-init)
    gen_hz_init
    ;;
  kitex)
    gen_kitex
    ;;
  # 兼容旧命令
  new)
    gen_hz_new
    ;;
  update)
    gen_hz_update
    ;;
  *)
    err "未知命令: $ACTION"
    ;;
esac

############################################
# 自动整理
############################################

log "执行 go mod tidy..."
go mod tidy

log "执行 go fmt..."
go fmt ./...

log "生成完成 ✅"
